"""add view_count to recipes

Revision ID: 8ebcdb7d1b3b
Revises: ca0f076e6008
Create Date: 2026-07-20 20:59:34.774375

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8ebcdb7d1b3b'
down_revision: Union[str, None] = 'ca0f076e6008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_recipes_view_count'), 'recipes', ['view_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_view_count'), table_name='recipes')
    op.drop_column('recipes', 'view_count')
    # ### end Alembic commands ###