"""add_partner_products

Revision ID: 9123a7bb38cb
Revises: f5f64fbeec69
Create Date: 2026-03-15 12:30:37.760142

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9123a7bb38cb'
down_revision: Union[str, None] = 'f5f64fbeec69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=True),
    sa.Column('store_logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_products')
    # ### end Alembic commands ###