"""add_suggested_status

Revision ID: 9e8cd3c2a04e
Revises: fa3c99505e72
Create Date: 2026-03-14 20:33:08.904150

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9e8cd3c2a04e'
down_revision: Union[str, None] = 'fa3c99505e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'show_daily_percent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'show_daily_percent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###