"""add yandex_id to user

Revision ID: ca0f076e6008
Revises: fbca842ac410
Create Date: 2026-07-17 19:40:09.217151

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ca0f076e6008'
down_revision: Union[str, None] = 'fbca842ac410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yandex_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_yandex_id'), 'users', ['yandex_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_yandex_id'), table_name='users')
    op.drop_column('users', 'yandex_id')
    # ### end Alembic commands ###