"""add_subscription_fields

Revision ID: f5f64fbeec69
Revises: 9e8cd3c2a04e
Create Date: 2026-03-14 21:06:50.977005

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f5f64fbeec69'
down_revision: Union[str, None] = '9e8cd3c2a04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_plan', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'subscription_plan')
    # ### end Alembic commands ###