"""add_user_kbju_stopwords

Revision ID: fa3c99505e72
Revises: c6d65348a34b
Create Date: 2026-03-12 21:19:30.786895

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fa3c99505e72'
down_revision: Union[str, None] = 'c6d65348a34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingredients_name_normalized_trgm', table_name='recipe_ingredients', postgresql_using='gin')
    op.drop_index('ix_ingredients_name_trgm', table_name='recipe_ingredients', postgresql_using='gin')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('daily_calories', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('daily_protein', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('daily_fat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('daily_carbs', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('show_daily_percent', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('users', sa.Column('stop_words', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stop_words')
    op.drop_column('users', 'show_daily_percent')
    op.drop_column('users', 'daily_carbs')
    op.drop_column('users', 'daily_fat')
    op.drop_column('users', 'daily_protein')
    op.drop_column('users', 'daily_calories')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_index('ix_ingredients_name_trgm', 'recipe_ingredients', ['name'], unique=False, postgresql_using='gin')
    op.create_index('ix_ingredients_name_normalized_trgm', 'recipe_ingredients', ['name_normalized'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###