"""add payment_method_id to users

Revision ID: fbca842ac410
Revises: cc852a7323fe
Create Date: 2026-06-08 17:11:50.314720

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fbca842ac410'
down_revision: Union[str, None] = 'cc852a7323fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payment_method_id', sa.String(length=64), nullable=True))
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.drop_column('users', 'payment_method_id')
    # ### end Alembic commands ###